from .communicate import CommunicationFormView
from .homepage import homepage
from .category import category
from .myspace import myspace
from .detail import DetailView
from .create_content import ContentCreateView
from .update_content import ContentUpdateView
from .delete_content import ContentDeleteView
from .delete_comment import delete_comment