version: "3.4"
services:
  gotya:
      build: .
      image: gotya
      container_name: gotya
      volumes:
        - ".:/gotya"
      ports:
        - "8000:8000"
      depends_on:
        - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
  