# Generated by Django 4.1.2 on 2022-10-28 14:03

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='content', unique=True)),
            ],
            options={
                'db_table': 'content',
            },
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
