# Generated by Django 4.1.2 on 2022-10-28 14:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gotya', '0002_contentmodel_delete_categorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
