# Generated by Django 4.1.2 on 2022-10-28 15:00

import autoslug.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gotya', '0003_alter_contentmodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tag',
            },
        ),
        migrations.AlterModelOptions(
            name='contentmodel',
            options={'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
        migrations.RenameField(
            model_name='contentmodel',
            old_name='name',
            new_name='header',
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='picture',
            field=models.ImageField(default=1, upload_to='content_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='header', unique=True),
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='tags',
            field=models.ManyToManyField(related_name='text', to='gotya.tagmodel'),
        ),
    ]
