# Generated by Django 4.1.2 on 2022-10-28 16:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gotya', '0006_alter_contentmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
