# Generated by Django 4.1.2 on 2022-10-29 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gotya', '0011_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
