# Generated by Django 4.1.2 on 2022-10-31 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gotya', '0012_contactmodel_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentmodel',
            old_name='edit_date',
            new_name='updated_date',
        ),
    ]
