# Generated by Django 4.1.2 on 2022-11-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotya', '0013_rename_edit_date_contentmodel_updated_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagModel',
            new_name='CategoryModel',
        ),
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='contentmodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='CategoryModels',
            field=models.ManyToManyField(related_name='content', to='gotya.categorymodel'),
        ),
        migrations.AlterModelTable(
            name='categorymodel',
            table='category',
        ),
    ]
