# Generated by Django 4.1.2 on 2022-12-25 20:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gotya', '0015_contentmodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
